name: Benchmark

on:
  # Run the workflow every day at midnight (00:00) UTC
  schedule:
    - cron: "0 0 * * *"
  # Enable manual trigger for easy debugging
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: "dagger-g2-main-4c"
    timeout-minutes: 10

    strategy:
      matrix:
        sdk: [go, python, typescript] # The SDKs you want to test

    steps:
      - name: dagger init (${{ matrix.sdk }})
        shell: bash
        run: |
          source /tmp/local-envs
          mkdir -p /tmp/benchmark
          cd /tmp/benchmark

          dagger --debug init --source=. --name=test --sdk=${{ matrix.sdk }}
        env:
          DAGGER_CLOUD_TOKEN: "dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw"

      - name: dagger functions@initial (${{ matrix.sdk }})
        shell: bash
        run: |
          source /tmp/local-envs
          cd /tmp/benchmark

          dagger --debug functions
        env:
          DAGGER_CLOUD_TOKEN: "dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw"

      - name: dagger functions@cached (${{ matrix.sdk }})
        shell: bash
        run: |
          source /tmp/local-envs
          cd /tmp/benchmark

          dagger --debug functions
        env:
          DAGGER_CLOUD_TOKEN: "dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw"

      - name: dagger functions@modified (${{ matrix.sdk }})
        shell: bash
        run: |
          source /tmp/local-envs
          cd /tmp/benchmark

          # invalidate the cache by modifying the source files
          for file in "main.go" "src/index.ts" "src/main/__init__.py"; do
            [ -f "$file" ] && echo >> $file
          done

          dagger --debug functions
        env:
          DAGGER_CLOUD_TOKEN: "dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw"
