name: Mirror Go SDK
on:
  push:
    branches:
      - test
    tags:
      - sdk/go/**
    paths:
      - "sdk/go/**"
      - .github/workflows/mirror-go-sdk.yml
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # Needed for go mod edit
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - run: |
          set -euo pipefail

          export FILTER_BRANCH_SQUELCH_WARNING=1

          git config user.name dagger-ci
          git config user.email hello@dagger.io

          git filter-branch -f --prune-empty \
            --subdirectory-filter sdk/go \
            --tree-filter "if [ -f go.mod ]; then go mod edit -dropreplace github.com/dagger/dagger; fi" \
            -- ${{ github.ref_name }}

          git remote add mirror "https://github.com/aluzzardi/dagger-go.git"

          GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git \
            -c "http.https://github.com/.extraheader=AUTHORIZATION: basic ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}" \
            push mirror $GITHUB_REF_NAME:"${GITHUB_REF_NAME/sdk\/go\//}"
