name: publish-sdk-go
on:
  push:
    branches:
      - main
    tags:
      - sdk/go/**
    paths:
      - "sdk/go/**"
      - .github/workflows/publish-go.yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: magefile/mage-action@v2
        with:
          version: latest
          args: sdk:go:publish ${{ github.ref_name }}
        env:
          GITHUB_PAT: ${{ secrets.RELEASE_DAGGER_CI_TOKEN }}
